// GENERATED by @edgedb/generate v0.3.3

import type {Executor} from "edgedb";

export type InsertSubnodeArgs = {
  "user": string;
  "body": string;
  "title": string;
  "links": string[];
};

export type InsertSubnodeReturns = {
  "id": string;
};

export function insertSubnode(client: Executor, args: InsertSubnodeArgs): Promise<InsertSubnodeReturns>;