// GENERATED by @edgedb/generate v0.3.3



export async function insertSubnode(client, args) {
  return client.queryRequiredSingle(`\
insert Subnode{
    user := <str>$user,
    body := <str>$body,
    node := (select Node filter .title = <str>$title ),
    links_to := (select Node filter .title in array_unpack(<array<str>>$links))
}`, args);

}