// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const $Subnode = $.makeType(_.spec, "99050ba5-422f-11ee-8922-c1bda4ad26e3", _.syntax.literal);

const Subnode= _.syntax.$PathNode($.$toSet($Subnode, $.Cardinality.Many), null);



export { $Subnode, Subnode };

const __defaultExports = {
  "Subnode": Subnode
};
export default __defaultExports;
