// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const AccessKind = $.makeType(_.spec, "6b784972-27fe-11ee-bcb9-b777a336bc32", _.syntax.literal);

const AccessPolicyAction = $.makeType(_.spec, "6b77a1e9-27fe-11ee-8284-0f8bd0e41400", _.syntax.literal);

const Cardinality = $.makeType(_.spec, "6b731ddd-27fe-11ee-a321-f3ba0a5756d4", _.syntax.literal);

const MigrationGeneratedBy = $.makeType(_.spec, "6b7b9363-27fe-11ee-bb89-6d523adc33eb", _.syntax.literal);

const OperatorKind = $.makeType(_.spec, "6b7514c3-27fe-11ee-b694-db6483202dca", _.syntax.literal);

const ParameterKind = $.makeType(_.spec, "6b765f63-27fe-11ee-9660-fbf4aca017cf", _.syntax.literal);

const RewriteKind = $.makeType(_.spec, "6b7af037-27fe-11ee-85a3-b1edb0ec4db2", _.syntax.literal);

const SourceDeleteAction = $.makeType(_.spec, "6b74735a-27fe-11ee-ad1d-8b6b33877557", _.syntax.literal);

const TargetDeleteAction = $.makeType(_.spec, "6b73c8d2-27fe-11ee-9f48-2de40579d8c5", _.syntax.literal);

const TriggerKind = $.makeType(_.spec, "6b799004-27fe-11ee-b80a-b5dbe4bf5b12", _.syntax.literal);

const TriggerScope = $.makeType(_.spec, "6b7a3090-27fe-11ee-98e5-87755617f081", _.syntax.literal);

const TriggerTiming = $.makeType(_.spec, "6b78edb2-27fe-11ee-a1fe-19ee79ebcf34", _.syntax.literal);

const TypeModifier = $.makeType(_.spec, "6b7700fa-27fe-11ee-9b5e-2fa88b566efb", _.syntax.literal);

const Volatility = $.makeType(_.spec, "6b75bd6e-27fe-11ee-93d4-39c5295f2822", _.syntax.literal);

const $Object_6b7c600a27fe11eeba3f8f7c5d042b90 = $.makeType(_.spec, "6b7c600a-27fe-11ee-ba3f-8f7c5d042b90", _.syntax.literal);

const Object_6b7c600a27fe11eeba3f8f7c5d042b90= _.syntax.$PathNode($.$toSet($Object_6b7c600a27fe11eeba3f8f7c5d042b90, $.Cardinality.Many), null);

const $SubclassableObject = $.makeType(_.spec, "6b869569-27fe-11ee-b03f-595903f8c977", _.syntax.literal);

const SubclassableObject= _.syntax.$PathNode($.$toSet($SubclassableObject, $.Cardinality.Many), null);

const $InheritingObject = $.makeType(_.spec, "6d1ed4ee-27fe-11ee-9027-0522a35c34b8", _.syntax.literal);

const InheritingObject= _.syntax.$PathNode($.$toSet($InheritingObject, $.Cardinality.Many), null);

const $AnnotationSubject = $.makeType(_.spec, "6cfa816a-27fe-11ee-b7f7-8b3126f088d9", _.syntax.literal);

const AnnotationSubject= _.syntax.$PathNode($.$toSet($AnnotationSubject, $.Cardinality.Many), null);

const $AccessPolicy = $.makeType(_.spec, "6e3b3930-27fe-11ee-903d-8fec1194a522", _.syntax.literal);

const AccessPolicy= _.syntax.$PathNode($.$toSet($AccessPolicy, $.Cardinality.Many), null);

const $Alias = $.makeType(_.spec, "6eb585a7-27fe-11ee-8120-8bf730860183", _.syntax.literal);

const Alias= _.syntax.$PathNode($.$toSet($Alias, $.Cardinality.Many), null);

const $Annotation = $.makeType(_.spec, "6d05a1ee-27fe-11ee-b41c-b12f108fae19", _.syntax.literal);

const Annotation= _.syntax.$PathNode($.$toSet($Annotation, $.Cardinality.Many), null);

const $Type = $.makeType(_.spec, "6b96ae83-27fe-11ee-bb9a-dbd912c82bc5", _.syntax.literal);

const Type= _.syntax.$PathNode($.$toSet($Type, $.Cardinality.Many), null);

const $PrimitiveType = $.makeType(_.spec, "6bccf01f-27fe-11ee-a233-2110b2141247", _.syntax.literal);

const PrimitiveType= _.syntax.$PathNode($.$toSet($PrimitiveType, $.Cardinality.Many), null);

const $CollectionType = $.makeType(_.spec, "6be10747-27fe-11ee-912d-cfe858586209", _.syntax.literal);

const CollectionType= _.syntax.$PathNode($.$toSet($CollectionType, $.Cardinality.Many), null);

const $Array = $.makeType(_.spec, "6bf52495-27fe-11ee-b72f-5b63e93bc700", _.syntax.literal);

const Array= _.syntax.$PathNode($.$toSet($Array, $.Cardinality.Many), null);

const $ArrayExprAlias = $.makeType(_.spec, "6c0eb1fe-27fe-11ee-89a3-8b36e9cab9db", _.syntax.literal);

const ArrayExprAlias= _.syntax.$PathNode($.$toSet($ArrayExprAlias, $.Cardinality.Many), null);

const $CallableObject = $.makeType(_.spec, "6d4b5f9b-27fe-11ee-a221-09bf6155a34b", _.syntax.literal);

const CallableObject= _.syntax.$PathNode($.$toSet($CallableObject, $.Cardinality.Many), null);

const $VolatilitySubject = $.makeType(_.spec, "6d656763-27fe-11ee-8283-2d56daadb7b4", _.syntax.literal);

const VolatilitySubject= _.syntax.$PathNode($.$toSet($VolatilitySubject, $.Cardinality.Many), null);

const $Cast = $.makeType(_.spec, "71712b03-27fe-11ee-b892-c9673b4df79a", _.syntax.literal);

const Cast= _.syntax.$PathNode($.$toSet($Cast, $.Cardinality.Many), null);

const $ConsistencySubject = $.makeType(_.spec, "6da29f91-27fe-11ee-ab05-63c312f99417", _.syntax.literal);

const ConsistencySubject= _.syntax.$PathNode($.$toSet($ConsistencySubject, $.Cardinality.Many), null);

const $Constraint = $.makeType(_.spec, "6d72842b-27fe-11ee-9f4a-8beff51e27d6", _.syntax.literal);

const Constraint= _.syntax.$PathNode($.$toSet($Constraint, $.Cardinality.Many), null);

const $Delta = $.makeType(_.spec, "6cec7dd9-27fe-11ee-8e03-3b70555ed27c", _.syntax.literal);

const Delta= _.syntax.$PathNode($.$toSet($Delta, $.Cardinality.Many), null);

const $Extension = $.makeType(_.spec, "71b9b762-27fe-11ee-bc59-433230d0587f", _.syntax.literal);

const Extension= _.syntax.$PathNode($.$toSet($Extension, $.Cardinality.Many), null);

const $Function = $.makeType(_.spec, "71186409-27fe-11ee-896f-27979107ab13", _.syntax.literal);

const Function= _.syntax.$PathNode($.$toSet($Function, $.Cardinality.Many), null);

const $FutureBehavior = $.makeType(_.spec, "71d5244c-27fe-11ee-b7ec-33e100986643", _.syntax.literal);

const FutureBehavior= _.syntax.$PathNode($.$toSet($FutureBehavior, $.Cardinality.Many), null);

const $Global = $.makeType(_.spec, "70f4d319-27fe-11ee-b5b4-0bd6ad781be1", _.syntax.literal);

const Global= _.syntax.$PathNode($.$toSet($Global, $.Cardinality.Many), null);

const $Index = $.makeType(_.spec, "6dc9d635-27fe-11ee-a808-6b31ff7ef1cf", _.syntax.literal);

const Index= _.syntax.$PathNode($.$toSet($Index, $.Cardinality.Many), null);

const $Pointer = $.makeType(_.spec, "6e09b70a-27fe-11ee-91f7-0bdf704a1626", _.syntax.literal);

const Pointer= _.syntax.$PathNode($.$toSet($Pointer, $.Cardinality.Many), null);

const $Source = $.makeType(_.spec, "6df55121-27fe-11ee-a237-57a7554e4bac", _.syntax.literal);

const Source= _.syntax.$PathNode($.$toSet($Source, $.Cardinality.Many), null);

const $Link = $.makeType(_.spec, "70155018-27fe-11ee-af83-c10a75338877", _.syntax.literal);

const Link= _.syntax.$PathNode($.$toSet($Link, $.Cardinality.Many), null);

const $Migration = $.makeType(_.spec, "71989892-27fe-11ee-802d-c3c345a41595", _.syntax.literal);

const Migration= _.syntax.$PathNode($.$toSet($Migration, $.Cardinality.Many), null);

const $Module = $.makeType(_.spec, "6bc2b8f6-27fe-11ee-ae51-737abd9885e6", _.syntax.literal);

const Module= _.syntax.$PathNode($.$toSet($Module, $.Cardinality.Many), null);

const $ObjectType = $.makeType(_.spec, "6f09cf2a-27fe-11ee-8dff-3b04d5355f1e", _.syntax.literal);

const ObjectType= _.syntax.$PathNode($.$toSet($ObjectType, $.Cardinality.Many), null);

const $Operator = $.makeType(_.spec, "7145c9b8-27fe-11ee-b1f1-ef129128d1ed", _.syntax.literal);

const Operator= _.syntax.$PathNode($.$toSet($Operator, $.Cardinality.Many), null);

const $Parameter = $.makeType(_.spec, "6d393505-27fe-11ee-81db-5dab2c1b65b5", _.syntax.literal);

const Parameter= _.syntax.$PathNode($.$toSet($Parameter, $.Cardinality.Many), null);

const $Property = $.makeType(_.spec, "706397d6-27fe-11ee-9850-4f973359d588", _.syntax.literal);

const Property= _.syntax.$PathNode($.$toSet($Property, $.Cardinality.Many), null);

const $PseudoType = $.makeType(_.spec, "6ba61833-27fe-11ee-af5c-6925c7f71256", _.syntax.literal);

const PseudoType= _.syntax.$PathNode($.$toSet($PseudoType, $.Cardinality.Many), null);

const $Range = $.makeType(_.spec, "6c6da22c-27fe-11ee-8725-d1c77d8c9ef7", _.syntax.literal);

const Range= _.syntax.$PathNode($.$toSet($Range, $.Cardinality.Many), null);

const $RangeExprAlias = $.makeType(_.spec, "6cd2efca-27fe-11ee-b6f0-0d223ba5aa58", _.syntax.literal);

const RangeExprAlias= _.syntax.$PathNode($.$toSet($RangeExprAlias, $.Cardinality.Many), null);

const $Rewrite = $.makeType(_.spec, "6e874ba9-27fe-11ee-b24f-a17ffd6f8b19", _.syntax.literal);

const Rewrite= _.syntax.$PathNode($.$toSet($Rewrite, $.Cardinality.Many), null);

const $ScalarType = $.makeType(_.spec, "6ece2851-27fe-11ee-95e7-814d48fc9eec", _.syntax.literal);

const ScalarType= _.syntax.$PathNode($.$toSet($ScalarType, $.Cardinality.Many), null);

const $Trigger = $.makeType(_.spec, "6e606a05-27fe-11ee-9b16-f9fa74ec9039", _.syntax.literal);

const Trigger= _.syntax.$PathNode($.$toSet($Trigger, $.Cardinality.Many), null);

const $Tuple = $.makeType(_.spec, "6c31440b-27fe-11ee-a747-45c6860ffae0", _.syntax.literal);

const Tuple= _.syntax.$PathNode($.$toSet($Tuple, $.Cardinality.Many), null);

const $TupleElement = $.makeType(_.spec, "6c274eab-27fe-11ee-91aa-e3898f1a3a0e", _.syntax.literal);

const TupleElement= _.syntax.$PathNode($.$toSet($TupleElement, $.Cardinality.Many), null);

const $TupleExprAlias = $.makeType(_.spec, "6c4e281a-27fe-11ee-94b3-01845f3a2d7a", _.syntax.literal);

const TupleExprAlias= _.syntax.$PathNode($.$toSet($TupleExprAlias, $.Cardinality.Many), null);



export { AccessKind, AccessPolicyAction, Cardinality, MigrationGeneratedBy, OperatorKind, ParameterKind, RewriteKind, SourceDeleteAction, TargetDeleteAction, TriggerKind, TriggerScope, TriggerTiming, TypeModifier, Volatility, $Object_6b7c600a27fe11eeba3f8f7c5d042b90, Object_6b7c600a27fe11eeba3f8f7c5d042b90, $SubclassableObject, SubclassableObject, $InheritingObject, InheritingObject, $AnnotationSubject, AnnotationSubject, $AccessPolicy, AccessPolicy, $Alias, Alias, $Annotation, Annotation, $Type, Type, $PrimitiveType, PrimitiveType, $CollectionType, CollectionType, $Array, Array, $ArrayExprAlias, ArrayExprAlias, $CallableObject, CallableObject, $VolatilitySubject, VolatilitySubject, $Cast, Cast, $ConsistencySubject, ConsistencySubject, $Constraint, Constraint, $Delta, Delta, $Extension, Extension, $Function, Function, $FutureBehavior, FutureBehavior, $Global, Global, $Index, Index, $Pointer, Pointer, $Source, Source, $Link, Link, $Migration, Migration, $Module, Module, $ObjectType, ObjectType, $Operator, Operator, $Parameter, Parameter, $Property, Property, $PseudoType, PseudoType, $Range, Range, $RangeExprAlias, RangeExprAlias, $Rewrite, Rewrite, $ScalarType, ScalarType, $Trigger, Trigger, $Tuple, Tuple, $TupleElement, TupleElement, $TupleExprAlias, TupleExprAlias };

const __defaultExports = {
  "AccessKind": AccessKind,
  "AccessPolicyAction": AccessPolicyAction,
  "Cardinality": Cardinality,
  "MigrationGeneratedBy": MigrationGeneratedBy,
  "OperatorKind": OperatorKind,
  "ParameterKind": ParameterKind,
  "RewriteKind": RewriteKind,
  "SourceDeleteAction": SourceDeleteAction,
  "TargetDeleteAction": TargetDeleteAction,
  "TriggerKind": TriggerKind,
  "TriggerScope": TriggerScope,
  "TriggerTiming": TriggerTiming,
  "TypeModifier": TypeModifier,
  "Volatility": Volatility,
  "Object": Object_6b7c600a27fe11eeba3f8f7c5d042b90,
  "SubclassableObject": SubclassableObject,
  "InheritingObject": InheritingObject,
  "AnnotationSubject": AnnotationSubject,
  "AccessPolicy": AccessPolicy,
  "Alias": Alias,
  "Annotation": Annotation,
  "Type": Type,
  "PrimitiveType": PrimitiveType,
  "CollectionType": CollectionType,
  "Array": Array,
  "ArrayExprAlias": ArrayExprAlias,
  "CallableObject": CallableObject,
  "VolatilitySubject": VolatilitySubject,
  "Cast": Cast,
  "ConsistencySubject": ConsistencySubject,
  "Constraint": Constraint,
  "Delta": Delta,
  "Extension": Extension,
  "Function": Function,
  "FutureBehavior": FutureBehavior,
  "Global": Global,
  "Index": Index,
  "Pointer": Pointer,
  "Source": Source,
  "Link": Link,
  "Migration": Migration,
  "Module": Module,
  "ObjectType": ObjectType,
  "Operator": Operator,
  "Parameter": Parameter,
  "Property": Property,
  "PseudoType": PseudoType,
  "Range": Range,
  "RangeExprAlias": RangeExprAlias,
  "Rewrite": Rewrite,
  "ScalarType": ScalarType,
  "Trigger": Trigger,
  "Tuple": Tuple,
  "TupleElement": TupleElement,
  "TupleExprAlias": TupleExprAlias
};
export default __defaultExports;
